---
title: "STA302 Assignment 2"
author: "Xinrui Wang"
date: "2019/10/11"
output:
  word_document: default
  html_document: default
  pdf_document: default
---
Q1
```{r, echo=TRUE, eval= FALSE}
#find extreme cases#
d_1 = read.csv("reale.csv")
attach(d_1)
summary(location)

dO_1 = d_1[c(1:104), c(2)]
dX_1 = d_1[c(105:163), c(2)]

boxplot(dO_1, main = "Boxplot of Sale Price in Neighbourhood O_0063", ylab = "Sale Price ($100k)")
boxplot(dX_1, main = "Boxplot of Sale Price in Neighbourhood X_0063", ylab = "Sale Price ($100k)")

max(dO_1, na.rm = FALSE)
min(dX_1, na.rm = FALSE)

#data subset#
dat = d_1[c(-99, -(104+48)), ]

#Scatterplots#
detach(d_1)
attach(dat)

library(ggplot2)

ggplot(data = dat, aes(x=list.price.in..100000, y = sale.price.in..100000, col = location))+geom_point()+ ggtitle("Scatterplot of Sale Price against List Price_0063")+xlab("List Price ($100k)")+ylab("Sale Price ($100k)")+geom_smooth(method="lm")+geom_point(size=2) 

ggplot(data = dat, aes(x=taxes, y = sale.price.in..100000, col = location))+geom_point()+ggtitle("Scatterplot of Sale Price against Taxes_0063")+xlab("Taxes") + ylab("Sale Price ($100k)")+geom_smooth(method="lm")+geom_point(size=2)
```

Q2
```{r, echo=TRUE, eval=FALSE}

ggplot(dat, aes(sample = sale.price.in..100000, colour = location))+stat_qq() +stat_qq_line() +ggtitle("QQ Plot of Sale Price in Both Neighbourhoods_0063")

ggplot(dat, aes(sample = log(sale.price.in..100000, base = 10), colour = location))+stat_qq() +stat_qq_line() +ggtitle("QQ Plot of Logarithm to Base 10 of Sale Price in Both Neighbourhoods_0063")

ggplot(dat, aes(sample = sqrt(sale.price.in..100000), colour = location))+stat_qq() +stat_qq_line() +ggtitle("QQ Plot of Square Root of Sale Price in Both Neighbourhoods_0063")

ggplot(dat, aes(sample = 1/(sale.price.in..100000), colour = location))+stat_qq() +stat_qq_line() +ggtitle("QQ Plot of Inverse of Sale Price in Both Neighbourhoods_0063")
```

Q3
```{r, echo=TRUE, eval= FALSE}
#simple linear regressions (SLR) for sale price from list price using all data#

l = lm(sale.price.in..100000 ~ list.price.in..100000, data = dat)
summary(l)

#Create two data frames for both neighbourhoods#

d_O = dat[location == 'O', ]
d_X = dat[location == 'X', ]

#simple linear regressions (SLR) for sale price from list price using properties of neighbourhood X#
l_X = lm(d_X$sale.price.in..100000 ~ d_X$list.price.in..100000, data = d_X)
summary(l_X)

#simple linear regressions (SLR) for sale price from list price using properties of neighbourhood O#
l_O = lm(d_O$sale.price.in..100000 ~ d_O$list.price.in..100000, data = d_O)
summary(l_O)

#95% confidence interval

confint(l, level=0.95)
confint(l_X, level=0.95)
confint(l_O, level=0.95)
```

Q4
```{r, echo=TRUE, eval=FALSE}
plot(list.price.in..100000, sale.price.in..100000, main='Scatterplot of Sale Price against List Price_0063', xlab = 'List Price ($100k)', ylab = 'Sale Price ($100k)')

abline(l,col = 'blue')
```

Q5
```{r, echo=TRUE, eval=FALSE}
#Estimated slope (b1)
# Neighbourhood O

b1_O = 0.926232 

# Neighbourhood X
b1_X = 0.90083

#MSE(S^2)
# Neighbourhood O
MSE_O = 0.233289

# Neighbourhood X
MSE_X = 0.1633776

#Calculate S_p

denom = length(d_O) + length(d_X) - 4

numer = (length(d_O)-2)* MSE_O + (length(d_X)-2)* MSE_X
  
S_p = sqrt(numer/denom)

#Calculate Test Statistic t_obs

SXX_O = sum((d_O$list.price.in..100000)^2)-length(d_O)*(mean(d_O$list.price.in..100000))^2

SXX_X = sum((d_X$list.price.in..100000)^2)-length(d_X)*(mean(d_X$list.price.in..100000))^2

d = S_p*sqrt(1/SXX_O + 1/SXX_X)
n = b1_O - b1_X

t_obs = n/d #under H0

p_val = 2*(1-pt(abs(t_obs), df = length(d_O)+length(d_X)-4))
```

Q6

```{r, echo=TRUE, eval=FALSE}

qqnorm(l_O$residuals, main = "QQ Plot of Residuals for Neighbourhood O_0063", pch=20)
qqline(l_O$residuals, col = "red")

```

