---
title: "USA Mobility (Apple)"
author: ''
date: ''
output:
  word_document: default
  html_document:
    df_print: paged
---
```{r,message=FALSE, cache = TRUE, echo = FALSE}

# Load the packages.
if (!require(xlsx)) {
  install.packages("xlsx")
}

if (!require(tidyverse)) {
  install.packages("tidyverse")
}

library(xlsx)
library(tidyverse)
library(ggplot2)
library(gridExtra)
```

```{r, cache = TRUE, echo = FALSE}

dat_A_US = as.data.frame(read.xlsx("Mobility_A.xlsx", sheetName = "Sample_Apple_UNITED STATES")) #US

#dat_A_CA = as.data.frame(read.xlsx("Mobility_A.xlsx", sheetName = "Sample_Apple_CANADA")) #CA

#can only load one dataset at a time
```

```{r,cache = TRUE, echo = FALSE}

#change the column names to dates
for(i in 7:length(names(dat_A_US))){
  num = substring(names(dat_A_US)[i], 2)
  names(dat_A_US)[i] = format(as.Date(as.numeric(num), origin = "1899-12-30"),format = "%Y-%m-%d")
  dat_A_US[, i] = (dat_A_US[, i] - 100)/100
}
```

```{r,cache = TRUE, echo = FALSE}
# compare with National Average Flow
pd = as.data.frame(t(as.matrix(dat_A_US[1:3,8:ncol(dat_A_US)])))
d = cbind(rownames(pd), data.frame(pd, row.names=NULL))
colnames(d) = c("Dates","driving", "transit", "walking")
d$Dates = as.Date(d$Dates)

# to plot for only one type:
p = ggplot(data = d, aes(x = Dates, y = transit)) + geom_line(color = "#00AFBB", size = 1) + xlab("") + ylab("Mobility (% change)") + ggtitle("Transit Mobility in USA") + theme_minimal() 

p + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + scale_x_date(date_labels = "%y %b %d") + geom_hline(yintercept = 0, linetype = "dashed") + geom_vline(xintercept = as.Date("2020-01-20"), color = "blue")

# to plot for two types:
df = d  %>%
  select(Dates, walking, driving) %>%
  gather(key = "Types", value = "value", -Dates)

p = ggplot(df, aes(x = Dates, y = value)) + geom_line(aes(color = Types), size = 1) + scale_color_manual(values = c("#228B22", "#E7B800")) + xlab("") + ylab("Mobility (% change)") + ggtitle("Walking and Driving Mobility in USA") + theme_minimal()

p + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + scale_x_date(date_labels = "%y %b %d") + geom_hline(yintercept = 0, linetype = "dashed") + geom_vline(xintercept = as.Date("2020-01-20"), color = "blue")
``` 

```{r, cache = TRUE, echo = FALSE}
# Compare with Inter-city Flows
s = sort(table(dat_A_US$sub.region), decreasing = TRUE)
# Choose the sub region New York as an example
sdat = dat_A_US %>%
  filter(sub.region == "New York") %>%
  filter(geo_type == "city")

pdat = as.data.frame(t(as.matrix(sdat[,8:ncol(sdat)])))
dat = cbind(rownames(pdat), data.frame(pdat, row.names=NULL))
colnames(dat) = c("Dates",as.vector(sdat[,3]))
dat$Dates = as.Date(dat$Dates)

# write a for loop: rearrange data set -> plot
num = unique(sdat$region) 
j = 1
plist = list()
for (i in 1:length(num)){
  
dd = cbind(dat$Dates, dat[,(3*i-1):(3*i+1)])
colnames(dd) = c("Dates","driving", "transit", "walking")
region = num[i]

p = ggplot(dd, aes(x = Dates, y = transit)) + geom_line(color = "#00AFBB", size = 1) + xlab("") + ylab("Mobility (% change)") + ggtitle(paste("Transit Mobility in", region)) + theme_minimal() 
p1 = p + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + scale_x_date(date_labels = "%y %b %d") + geom_hline(yintercept = 0, linetype = "dashed") + geom_vline(xintercept = as.Date("2020-01-20"), color = "blue")

dd2 = dd  %>%
  select(Dates, walking, driving) %>%
  gather(key = "Types", value = "value", -Dates)

pp = ggplot(dd2, aes(x = Dates, y = value)) + geom_line(aes(color = Types), size = 1) + scale_color_manual(values = c("#228B22", "#E7B800")) + xlab("") + ylab("Mobility (% change)") + ggtitle(paste("Walking and Driving Mobility in", region)) + theme_minimal()
p2 = pp + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + scale_x_date(date_labels = "%y %b %d") + geom_hline(yintercept = 0, linetype = "dashed") + geom_vline(xintercept = as.Date("2020-01-20"), color = "blue")

plist[[j]] = p1
plist[[j + 1]] = p2
j = j + 2
}

do.call("grid.arrange", c(plist, ncol = 2))
```

