---
title: "Remove Seasonality"
author: ''
date: ''
output:
  word_document: default
  html_document:
    df_print: paged
---
```{r, echo = TRUE, eval = TRUE, message = FALSE}
packages = c("xlsx", "tidyverse", "viridis", "forecast", "fpp", "ggfortify", "zoo", "xts", "forecast", "TTR")
#install.packages(packages)
lapply(packages, library, character.only = TRUE)
```

```{r, cache = TRUE, echo = FALSE, message = FALSE}

dat_A_US = as.data.frame(read.xlsx("Mobility_A.xlsx", sheetName = "Sample_Apple_UNITED STATES")) #US

reg_info_A = as.data.frame(read.xlsx("US State-Level Regulations_A.xlsx", sheetName = "State-Level Regulations_A"))
```

```{r,cache = TRUE, echo = FALSE, message = FALSE, error = FALSE}

#change the column names to dates
for(i in 7:length(names(dat_A_US))){
  num = substring(names(dat_A_US)[i], 2)
  names(dat_A_US)[i] = format(as.Date(as.numeric(num), origin = "1899-12-30"),format = "%Y-%m-%d")
  dat_A_US[, i] = (dat_A_US[, i] - 100)
}

for(i in 1:length(rownames(reg_info_A))){
  nname = gsub("Â\\s", "", reg_info_A$State.Territory[i])
  reg_info_A[i, 1] = nname
}
#change "No" to NA & notice some entries are not exact dates
for(i in 1:nrow(reg_info_A)){
  for(j in 2:ncol(reg_info_A)){
    if (typeof(reg_info_A[i,j]) != "double"){
      reg_info_A[i,j] = format(as.Date(as.numeric(reg_info_A[i,j]), origin = "1899-12-30"), format = "%Y-%m-%d")
      }
    else if (typeof(reg_info_A[i,j]) == "double"){
      reg_info_A[i,j] = as.character(reg_info_A[i,j])}
    }
}
reg_info_A = reg_info_A %>%
  mutate_all(as.character)

colnames(reg_info_A) = as.character(c("State.Territory", "State.of.Emergency", "Stay-at-Home", "Face.Coverings", "Gatherings", "Out-of-State.Travel", "Schools.Closure", "Bar&Sit-Down Restaurants.Closure", "Other.Facilities.Closure"))
```

## Plot for Any State
```{r,cache = TRUE, echo = FALSE, message = FALSE}
S = toupper(readline(prompt = "Enter State: "))
pd = dat_A_US %>%
  filter(toupper(region) == S)
pd = as.data.frame(t(as.matrix(pd[,7:ncol(pd)])))
pd = cbind(rownames(pd), data.frame(pd, row.names = NULL))
colnames(pd) = c("Dates","Driving")
pd$Dates = as.Date(pd$Dates)

#remove seasonality using SMA()
example_d = na.omit(pd)
pd1 = xts(example_d$Driving, as.Date(example_d$Dates, format = '%Y-%m-%d'))
s_wk = SMA(pd1, n = 7) 
s_mth = SMA(pd1, n = 30) 

#regulation info
reg_info.new = reg_info_A %>%
  filter(toupper(State.Territory) == S) %>%
  .[,2:ncol(reg_info_A)] %>%
  mutate(Dates = rownames(.)) %>%
  gather(key = "Regulation", value = "Dates", -Dates)
reg_info.new$Dates = as.Date(reg_info.new$Dates)
``` 

```{r,cache = TRUE, echo = FALSE, message = FALSE}
# to plot for state S + regulation timeline:
len = nrow(reg_info.new)

p1 = autoplot(s_wk) + xlab("") + ylab("% Change in Mobility") + ggtitle(paste("Adjusted %Change in Driving Mobility of State", S, "(n = 7)"))
p1 = p1 + geom_vline(data = reg_info.new, mapping = aes(xintercept = as.POSIXct(reg_info.new[, 2], tz = "UTC"), colour = Regulation), size = 0.7, show.legend = TRUE) + geom_hline(yintercept = 0, size = 1, linetype = "dashed", colour = "Red") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + scale_x_date(date_labels = "%y %b %d") #x-intercept needs to have the same form as the time(s_wk)

p2 = autoplot(s_mth) + xlab("") + ylab("% Change in Mobility") + ggtitle(paste("Adjusted %Change in Driving Mobility of State", S, "(n = 30)")) 
p2 = p2 + geom_vline(data = reg_info.new, mapping = aes(xintercept = as.POSIXct(reg_info.new[, 2], tz = "UTC"), colour = Regulation), size = 0.7, show.legend = TRUE) + geom_hline(yintercept = 0, size = 1, linetype = "dashed", colour = "Red") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + scale_x_date(date_labels = "%y %b %d")
```

## For the all states in USA
```{r, cache = TRUE, echo = FALSE, message = FALSE}
pd2 = dat_A_US %>%
  filter(geo_type == "sub-region")
pd3 = as.data.frame(t(as.matrix(pd2[, 7:ncol(pd2)]))) 
pd3 = cbind(rownames(pd3), data.frame(pd3, row.names = NULL))
colnames(pd3) = c("Dates", pd2$region)
pd3$Dates = as.Date(pd3$Dates)
pd3 = na.omit(pd3)

#remove seasonality for each state (n=7)
ust_wk = pd3
i = 2
while (i <= ncol(ust_wk)){
  ust_wk[,i] = SMA(ust_wk[,i], n = 7)
  i = i + 1
}
ust_wk = na.omit(ust_wk)

#plot
usapd_wk = ust_wk  %>%
  select(Dates, pd2$region) %>%
  gather(key = "States", value = "Value", -Dates)
p3 = ggplot(usapd_wk, aes(x = Dates, y = Value)) + geom_line(aes(color = States), size = 0.1) + xlab("") + ylab("Mobility (% change)") + ggtitle("Adjusted %Change in Driving Mobility in USA (n = 7)") + theme_minimal()

#check if there's entry > 2
sl_wk = c("")
for (i in 1:nrow(usapd_wk)){
  if(usapd_wk[i,3] > 2){
    sl_wk = paste(sl_wk, usapd_wk[i,2])
  }
}

#n = 30
ust_mth = pd3
i = 2
while (i <= ncol(ust_mth)){
  ust_mth[,i] = SMA(ust_mth[,i], n = 30)
  i = i + 1
}
ust_mth = na.omit(ust_mth)

#plot
usapd_mth = ust_mth  %>%
  select(Dates, pd2$region) %>%
  gather(key = "States", value = "Value", -Dates)

#check if there's entry > 2
sl_mth = c("")
for (i in 1:nrow(usapd_mth)){
  if(usapd_mth[i,3] > 2){
    sl_mth = paste(sl_mth, usapd_mth[i,2])
  }
}

p4 = ggplot(usapd_mth, aes(x = Dates, y = Value)) + geom_line(aes(color = States), size = 0.1) + xlab("") + ylab("Mobility (% change)") + ggtitle("Adjusted %Change in Driving Mobility in USA (n = 30)") + theme_minimal()
```

# Add a line for the entire USA
```{r, cache = TRUE, echo = FALSE, message = FALSE}
usad = dat_A_US %>%
  subset(geo_type == "country/region" & transportation_type == "driving")
usad = as.data.frame(t(as.matrix(usad[, 7:ncol(usad)])))
usad = cbind(rownames(usad), data.frame(usad, row.names = NULL))
colnames(usad) = c("Dates","Driving")
usad = na.omit(usad)
#black line is the USA in general
#n = 7
usad_wk = as.data.frame(cbind(as.character(usad$Dates), SMA(usad$Driving, n = 7)))%>% na.omit()
colnames(usad_wk) = c("Dates","Driving")
usad_wk$Dates = as.Date(usad_wk$Dates)
p5 = p3 + geom_line(aes(Dates, as.numeric(Driving)), usad_wk, size = 1) + geom_hline(yintercept = 0, size = 1, linetype = "dashed", colour = "Red") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + scale_x_date(date_labels = "%y %b %d") 

#n = 30
usad_mth = as.data.frame(cbind(as.character(usad$Dates), SMA(usad$Driving, n = 30)))%>% na.omit()
colnames(usad_mth) = c("Dates","Driving")
usad_mth$Dates = as.Date(usad_mth$Dates)
p6 = p4 + geom_line(aes(Dates, as.numeric(Driving)), usad_mth, size = 1) + geom_hline(yintercept = 0, size = 1, linetype = "dashed", colour = "Red") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + scale_x_date(date_labels = "%y %b %d") 
```

#compare selected states
```{r, cache = TRUE, echo = FALSE, message = FALSE}
pd = dat_A_US %>%
  filter(region == "Wyoming")
pd = as.data.frame(t(as.matrix(pd[,7:ncol(pd)])))
pd = cbind(rownames(pd), data.frame(pd, row.names = NULL))
colnames(pd) = c("Dates","Driving")
pd$Dates = as.Date(pd$Dates)

#remove seasonality using SMA()
example_d = na.omit(pd)
pd1 = xts(example_d$Driving, as.Date(example_d$Dates, format = '%Y-%m-%d'))
s_wk2 = SMA(pd1, n = 7) 
s_wk3 = as.data.frame(cbind(na.omit(s_wk), na.omit(s_wk2)))
colnames(s_wk3) = c("Mississippi", "Wyoming")
s_wk4 = s_wk3 %>%
  mutate(Dates = rownames(.)) %>%
  gather(key = "States", value = "Value", -Dates)
s_wk4$Dates = as.Date(s_wk4$Dates)

p7 = ggplot(s_wk4, aes(x = Dates, y = Value)) + geom_line(aes(color = States), size = 0.1) + xlab("") + ylab("Mobility (% change)") + ggtitle("Compare Adjusted Driving Mobility in 2 States (n = 7)") + theme_minimal() + geom_hline(yintercept = 0, size = 1, linetype = "dashed", colour = "Red") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + scale_x_date(date_labels = "%y %b %d")
```

```{r, cache = TRUE, echo = FALSE, message = FALSE}
# Investigate each county/city
hd = dat_A_US %>%
  filter(sub.region == "Wyoming")
pd4 = as.data.frame(t(as.matrix(hd[,7:ncol(hd)])))
pd4 = cbind(rownames(pd4), data.frame(pd4, row.names = NULL))
colnames(pd4) = c("Dates", hd$region)
pd4$Dates = as.Date(pd4$Dates)
pd4 = na.omit(pd4)

#remove seasonality for each county (n=7)
ust_wk2 = pd4
i = 2
while (i <= ncol(ust_wk2)){
  ust_wk2[,i] = SMA(ust_wk2[,i], n = 7)
  i = i + 1
}
ust_wk2 = na.omit(ust_wk2)

#remove seasonality for each county (n=30)
ust_mth2 = pd4
i = 2
while (i <= ncol(ust_mth2)){
  ust_mth2[,i] = SMA(ust_mth2[,i], n = 30)
  i = i + 1
}
ust_mth2 = na.omit(ust_mth2)

#plot
shadesOfGrey = colorRampPalette(c("grey0", "grey70"))
usapd_wk2 = ust_wk2  %>%
  select(Dates, hd$region) %>%
  gather(key = "County", value = "Value", -Dates)

p8 = ggplot(usapd_wk2, aes(x = Dates, y = Value)) + geom_line(aes(color = County), size = 0.1) + xlab("") + ylab("Mobility (% change)") + ggtitle("Adjusted %Change of Driving Mobility in Wyoming Counties (n = 7)") + theme_minimal()

p10 = p8 + geom_vline(xintercept = reg_info.new$Dates, colour = shadesOfGrey(nrow(reg_info.new)), size = 0.7, linetype = "dashed") + geom_text(data = reg_info.new, mapping = aes(x = Dates, y = 400, label = Regulation), angle = 90, size = 3) + geom_hline(yintercept = 0, size = 1, linetype = "dashed", colour = "Red") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + scale_x_date(date_labels = "%y %b %d")

usapd_mth2 = ust_mth2  %>%
  select(Dates, hd$region) %>%
  gather(key = "County", value = "Value", -Dates)

p9 = ggplot(usapd_mth2, aes(x = Dates, y = Value)) + geom_line(aes(color = County), size = 0.1) + xlab("") + ylab("Mobility (% change)") + ggtitle("Adjusted %Change of Driving Mobility in Wyoming Counties (n = 30)") + theme_minimal()

p11 = p9 + geom_vline(xintercept = reg_info.new$Dates, colour = shadesOfGrey(nrow(reg_info.new)), size = 0.7, linetype = "dashed") + geom_text(data = reg_info.new, mapping = aes(x = Dates, y = 400, label = Regulation), angle = 90, size = 3) + geom_hline(yintercept = 0, size = 1, linetype = "dashed", colour = "Red") + theme(axis.text.x = element_text(angle = 45, hjust = 1)) + scale_x_date(date_labels = "%y %b %d")

L1 = usapd_wk2$County[order(usapd_wk2$Value, decreasing = T)[1]]
#Park County
L2 = usapd_mth2$County[order(usapd_mth2$Value, decreasing = T)[1]]
#Park County
```

